### ISSUE TITLE
K9s install failing now due to missing checksum txt file in new release

### ISSUE THREAD

**Issue by jlian** [rio/features#39]
K9s [v0.28.0](https://github.com/derailed/k9s/releases/tag/v0.28.0) is out and instead of checksum.txt it's now [checksums.sha256](https://github.com/derailed/k9s/releases/download/v0.28.0/checksums.sha256)

The feature current fails when https://github.com/derailed/k9s/releases/download/v0.28.0/checksums.txt 404s

**Comment by rio** [comment]
This is the third time this happens to a package I manage. These open source tool builders are out of control! ;)

I'll take a look when I get the time. Thanks for submitting.

**Comment by rio** [comment]
Pinned the default version to 0.27.4 for now.

**Comment by rio** [comment]
Never mind, just fixed it.
