### ISSUE TITLE
K9s >= 0.29.0 install failing due to (another) new checksum format

### ISSUE THREAD

**Issue by c-ryan-k** [rio/features#47]
Similar to issue #39 - in version [0.29.0](https://github.com/derailed/k9s/releases/tag/v0.29.0) derailed has added checksums for additional files (namely SBOM files) and it looks like the checksum validations are failing again.

In our case, the checksum validation for `k9s_Linux_amd64.tar.gz` was actually trying to validate the checksum for `k9s_Linux_amd64.tar.gz.sbom` :
![image](https://github.com/rio/features/assets/13545962/bb2d9c74-021d-45b7-8980-58858635781e)

For now we're going to pin to v0.28.2, but hopefully this is an easy fix in the install script

Thanks for hosting this :)

**Comment by rio** [comment]
Thanks for reporting! Just now ran into the same thing ;)

Running the test suite again also caught the exact same problem for vcluster! 2 birds, one stone etc.
I'm running the release pipeline in a bit.

> Thanks for hosting this :)

These words also really help :)
